homebrew_taps: []

homebrew_package_removals: []

homebrew_packages:
- autoconf
- awscli
- bash
- bash-completion@2
- binutils
- brotli
- c-ares
- cfssl
- colordiff
- coreutils
- cowsay
- ctags
- curl
- curl-openssl
- dep
- docbook
- docbook-xsl
- dos2unix
- findutils
- freetype
- fx
- fzf
- gdbm
- gettext
- ghostscript
- git
- git-extras
- glib
- gnu-getopt
- go
- helm
- htop
- hyperkit
- icu4c
- ilmbase
- imagemagick
- jansson
- jemalloc
- jpeg
- jq
- kind
- kubernetes-cli
- lesspipe
- libdev265
- libev
- libevent
- libffi
- libheif
- libidn
- libidn2
- libmetalink
- libomp
- libpng
- libssh2
- libtiff
- libtool
- libunistring
- libyaml
- libzip
- little-cms2
- lua
- minikube
- moreutils
- ncurses
- neofetch
- nghttp2
- node
- oniguruma
- openexr
- openjpeg
- openldap
- openssl@1.1
- pcre
- pcre2
- perl
- pkg-config
- powerlevel9k
- putty
- pv
- pyenv
- pypy
- python
- python@3.8
- readline
- reattach-to-user-namespace
- redis
- rtmpdump
- ruby
- screenresolution
- sfnt2woff
- sfnt2woff-zopfli
- shellcheck
- sqlite
- ssh-copy-id
- telnet
- terraform
- the_silver_searcher
- tldr
- tmux
- tree
- vim
- watch
- webkit2ng
- webp
- wget
- woff2
- x265
- xmlto
- xz
- z
- zlib
- zsh
- zsh-completions
- zsh-syntax-highlighting

homebrew_cask_packages:
- '0xed'
- alfred
- docker
- font-fira-code
- font-hack-nerd-font
- google-chrome
- iterm2
- macdown
- macvim
- postman
- spectacle
- sublime-text
- the-unarchiver
- vagrant
- vagrant-manager
- virtualbox
- visual-studio-code

pyenv_python_versions:
# In precedence order
- 3.7.7
- 2.7.17

pip_packages:
- 2to3
- ansible
- astroid
- boto
- boto3
- cachetools
- certifi
- cffi
- chardet
- cryptography
- google-auth
- hjson
- idna
- isort
- Jinja2
- lazy-object-proxy
- MarkupSafe
- mccabe
- mypy
- mypy-extensions
- pbr
- pip
- pipenv
- pyasn1
- pyasn1-modules
- pycparser
- pylint
- PyYAML
- redis
- requests
- rsa
- setuptools
- six
- stevedore
- typed-ast
- typing-extensions
- urllib3
- virtualenv
- virtualenv-clone
- virtualenvwrapper
- wheel
- wrapt

## gem query --local
gem_packages:
- bigdecimal
- bundler
- CFPropertyList
- clocale
- cmath
- colorls
- csv
- date
- dbm
- did_you_mean
- e2mmap
- etc
- fcntl
- fiddle
- filesize
- fileutils
- forwardable
- io-console
- ipaddr
- irb
- json
- libxml
- logger
- manpages
- matrix
- mini_portile2
- minitest
- mutex_m
- net-telnet
- nokogiri
- openssl
- ostruct
- power_assert
- prime
- psych
- rainbow
- rake
- rdoc
- rexml
- rss
- scanf
- sdbm
- shell
- sqlite3
- stringio
- strscan
- sync
- test-unit
- thwait
- tracer
- webrick
- xmlrpc
- zlib
