- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
  - config
  - config/yamllint

- name: dotfiles links
  file:
    src: '{{ ansible_env.PWD }}/roles/short_mac/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
  - config/yamllint/config
  - CFUserTextEncoding
  - DS_Store
  - Xauthority
  - anyconnect
  - bash_profile
  - bashrc
  - boto
  - condarc
  - fzf.bash
  - fzf.zsh
  - p10k.zsh
  - python_history
  - rediscli_history
  - shell.pre-oh-my-zsh
  - tmux.conf
  - vim_mru_files
  - viminfo
  - vimrc
  - zsh_history
  - zshrc
